### ISSUE TITLE
App keeps crashing

### ISSUE THREAD

**Issue by krisstakos** [rizlas/open-auto-pro-sync#6]
Hi, great concept! I see a lot of potential.
What's the problem:
The app is installed wihout problems, opens without problems but keep force-closing when I press any of the buttons in it.
e.g. I'm pressing 'get gps data' -> force-close crash (it worked like on the 10th time)
when a got the GPS coordinates I pressed 'get sunrise/sunset' button and again -> force-close crash (never worked)
My phone details:
OnePlus 5 -> Stock Android 10

**Comment by rizlas** [comment]
Hi,
thank you for reporting this. I just debugged on Android 10 and fixed the issue. Please download and try with the new apk and let me know if it's all good now.

Download apk inside xamarin-android-app branch or click [Apk here](https://github.com/rizlas/open-auto-pro-sync/blob/xamarin-android-app/OpenAutoProSync.apk)

**Comment by krisstakos** [comment]
Awesome, now is working - kinda. So I setup everything on the RPI  and can confirm that it's wokring. But when I press "get sunrise and sunset time" button the response is always "Something went wrong".

**Comment by rizlas** [comment]
If you enabled storage permission, in your internal storage, you should see a log file under the folder _OapSync_. Please copy and paste here the content.

**Comment by krisstakos** [comment]
[2021-03-12.log](https://github.com/rizlas/open-auto-pro-sync/files/6132917/2021-03-12.log)
[2021-03-11.log](https://github.com/rizlas/open-auto-pro-sync/files/6132918/2021-03-11.log)
Here you go, I have couple feature suggestions. Where should I post them?

**Comment by rizlas** [comment]
For it I would suggest the openautopro forum

**Comment by rizlas** [comment]
> 
> 
> [2021-03-12.log](https://github.com/rizlas/open-auto-pro-sync/files/6132917/2021-03-12.log)
> [2021-03-11.log](https://github.com/rizlas/open-auto-pro-sync/files/6132918/2021-03-11.log)
> Here you go, I have couple feature suggestions. Where should I post them?

Just download new [apk](https://github.com/rizlas/open-auto-pro-sync/blob/xamarin-android-app/OpenAutoProSync.apk) and se me again log file please. Still not solved but I need to read the URI that is being formed.

**Comment by krisstakos** [comment]
Hi, sure no problem. Here you go (btw removed my coordinates and replaced it with zeros for privacy).
`[ERROR] - 12:22:57.5129 - BT_OAP_Service.MainActivity:
Response ErrorMessage: Error: ConnectFailure (The requested address is not valid in this context) StatusCode: 0 FullUrl: https://api.sunrise-sunset.org/json?lat=00.0000&lng=00.0000`
the url was working alright checked it on my browser:
`{"results":{"sunrise":"4:40:48 AM","sunset":"4:31:15 PM","solar_noon":"10:36:01 AM","day_length":"11:50:27","civil_twilight_begin":"4:12:48 AM","civil_twilight_end":"4:59:15 PM","nautical_twilight_begin":"3:40:02 AM","nautical_twilight_end":"5:32:01 PM","astronomical_twilight_begin":"3:06:50 AM","astronomical_twilight_end":"6:05:13 PM"},"status":"OK"}`

**Comment by rizlas** [comment]
Ah thank you. I was concerned about privacy too. That's error is really strange, for me is working fine. Same result over both Wi-Fi and mobile data?

**Comment by krisstakos** [comment]
Yes, it's the same error on both - Wifi and MobileData

**Comment by krisstakos** [comment]
I've found an old post that can shine a little bit of light on the problem:
`Due to increased security requirements, including PCI compliance, major cloud providers and web servers are expected to stop supporting TLS versions older than 1.2. Xamarin projects created in previous versions of Visual Studio default to use older versions of TLS.
you can search on: HttpClient Stack and SSL/TLS Implementation Selector for Android`
I guess you are running an old version of Android 8? and mine is Android 10

**Comment by rizlas** [comment]
I tried to force TLS 1.2 in compiler and before requests. Let me know if something changed. Good hint btw, thank you.

I also debugged with a redmi note 7 running android 10 but i wasn't able to replicate the error. I don't think is releated to android versions.

**Comment by krisstakos** [comment]
So sad, it didn't worked. Tried debugging myself with no luck... dunno what's wrong. If it's not from android version and all security stuff what it could be? I'm narrowig it down to old version of xamarin? - which doen't support fully android 10? RestClient is not fully supported on android 10? duno...

**Comment by rizlas** [comment]
Currently the project is targeting android 9 but i don't think this could be an issue. I just debugged it on a OnePlus 7 with Android 10 without encountering any error. Let me ask you some questions:

- did you try to run the app on another phone? Maybe with the same carrier or same wifi connection
- Do you have root?
- Did you try http instead https during debugging? 
- Do you receive temperature data?

**Comment by krisstakos** [comment]
1. did you try to run the app on another phone? Maybe with the same carrier or same wifi connection - I can try with another phone on the same wifi
2. Do you have root? - Yes, I have (tried hiding it but the result was the same)
3. Did you try http instead https during debugging? Yes, tried http and https also with explicitly defined ports :80/:443
4. Do you receive temperature data? Yes, I'm receiving it

**Comment by rizlas** [comment]
> 
>     4. Do you receive temperature data? Yes, I'm receiving it

This is really strange! Same libraries are used to retrieve temperature data.

**Comment by rizlas** [comment]
Just try the latest apk. I replaced sunrise-sunset.org api with the same api service that i'm using for temperature data. You should not have any problem now. Let me know. Thank you.

**Comment by krisstakos** [comment]
Works like a charm now! Thank you!

**Comment by rizlas** [comment]
Thank you for pointing it out. In the next few days i'm going to rework the sync process, if you have other stuff in mind pull requests are always welcome.

Thank you!
